# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdfd95f7725781b02a22c8ed4776819b3d2036899a09f997985d3a198164913110acf981ba83906b00024169d424d9b38a966d66c7a99f0a48b8906d54f96a55

test:
  secret_key_base: 5e4cbab357629e3a725ae473a2e486e4e2bc9352214882b5ed9eb6a6358b2a798fe61cf37a85af606783eea2d34d146ce32bf15360b6454841eacb4a6b22ea5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
